// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntjdbhfmsihpldyqyknq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50amRiaGZtc2locGxkeXF5a25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDY2MTgsImV4cCI6MjA1OTY4MjYxOH0.QuYnUK7Q4HFyZG21QKLCoQdTrEIf-KTAhcgjAU0s6Q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);